"""Initial migration.

Revision ID: 06967a7e1d32
Revises: 
Create Date: 2020-12-08 21:26:44.314478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06967a7e1d32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=240), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_status', sa.Enum('applied', 'rejected', 'no_response', 'interview', 'accepted', 'pending', name='jobstatus'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Job')
    op.drop_table('User')
    # ### end Alembic commands ###
